name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        go_version: [1.15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: autocannon-go
          targets: linux/amd64
          v: true
          x: false
          ldflags: -s -w
      - name: Run Template
        run: main --production
      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.3.0/deck_1.3.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/
          deck validate
      - name: decK Sync
        run: deck sync
      - name: Run Cypress testing
        run: |
          npm init
          npm i cypress
          npm run cypress:open
